// Pure transform: design-tokens.json -> CSS custom properties. No filesystem
// I/O here on purpose, so both build-tokens.mjs (writes the file) and
// check-tokens-drift.mjs (compares hashes without writing) share one
// generator and can never drift from each other.

function kebab(str) {
  return str.replace(/([a-z0-9])([A-Z])/g, '$1-$2').toLowerCase();
}

function colorVars(colorObj) {
  return Object.entries(colorObj)
    .filter(([key]) => !key.startsWith('_'))
    .map(([key, value]) => `  --color-${kebab(key)}: ${value};`)
    .join('\n');
}

function brandVars(brand) {
  const lines = [];
  for (const [rampName, ramp] of Object.entries(brand)) {
    for (const [step, hex] of Object.entries(ramp)) {
      lines.push(`  --color-${kebab(rampName)}-${step}: ${hex};`);
    }
  }
  return lines.join('\n');
}

// Only two font-family roles exist today (display, ui); a static fallback
// map is simpler and safer than trying to infer generic families from data.
const GENERIC_FALLBACK = {
  display: 'Georgia, serif',
  ui: '-apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif',
};

function fontFamilyVars(fontFamilies) {
  return Object.entries(fontFamilies)
    .map(([role, def]) => {
      const fallback = GENERIC_FALLBACK[role] ?? 'sans-serif';
      return `  --font-family-${kebab(role)}: '${def.family}', '${def.devanagariCompanion}', ${fallback};`;
    })
    .join('\n');
}

function typeRoleVars(typography) {
  const lines = [];
  for (const [role, def] of Object.entries(typography)) {
    if (role === 'note' || role === 'fontFamilies') continue;
    const r = kebab(role);
    const familyRole = def.family === typography.fontFamilies.display.family ? 'display' : 'ui';
    lines.push(`  --text-${r}-family: var(--font-family-${familyRole});`);
    lines.push(`  --text-${r}-weight: ${def.weight};`);
    lines.push(`  --text-${r}-size: ${def.size}px;`);
    lines.push(`  --text-${r}-line-height: ${def.heightMultiplier};`);
    lines.push(`  --text-${r}-tracking: ${def.letterSpacing}px;`);
  }
  return lines.join('\n');
}

function scaleVars(prefix, obj) {
  return Object.entries(obj)
    .map(([key, value]) => `  --${prefix}-${key}: ${value}px;`)
    .join('\n');
}

function elevationVars(elevation) {
  return elevation.levels
    .map(
      (l) =>
        `  --elevation-${l.level}-tint-opacity: ${l.darkSurfaceTintOpacity};\n` +
        `  --elevation-${l.level}-shadow: ${l.lightShadow};`,
    )
    .join('\n');
}

function motionVars(motion) {
  const lines = [];
  for (const [key, value] of Object.entries(motion.duration)) {
    lines.push(`  --duration-${kebab(key)}: ${value}ms;`);
  }
  for (const [key, value] of Object.entries(motion.easing)) {
    if (key === 'banned') continue;
    lines.push(`  --easing-${kebab(key)}: ${value};`);
  }
  return lines.join('\n');
}

export function generateTokensCss(tokens) {
  const { color, typography, spacing, radius, elevation, motion, meta } = tokens;

  return `/* AUTO-GENERATED by scripts/build-tokens.mjs from design-tokens.json
 * (source: dhruva-app v${meta.version}). Do not hand-edit.
 * Run \`npm run build:tokens\` to regenerate; \`npm run tokens:check\` (wired
 * into CI) fails the build if this file drifts from the source JSON. */

:root {
  color-scheme: dark light;

  /* spacing */
${scaleVars('space', spacing)}

  /* radius */
${scaleVars('radius', radius)}

  /* motion */
${motionVars(motion)}

  /* elevation */
${elevationVars(elevation)}

  /* typography: font stacks */
${fontFamilyVars(typography.fontFamilies)}

  /* typography: type roles */
${typeRoleVars(typography)}

  /* brand ramps (theme-independent) */
${brandVars(color.brand)}

  /* color: dark theme (default — dark is the hero theme) */
${colorVars(color.dark)}
}

@media (prefers-color-scheme: light) {
  :root {
    /* color: light theme override */
${colorVars(color.light)}
  }
}
`;
}
